### ISSUE TITLE
@pnpm/exec install failing

### ISSUE THREAD

**Issue by davej** [zkochan/package-preview#17]
```
 ! Cannot convert undefined or null to object

Error: Exit code: 1
    at ChildProcess.proc.on (/Users/dave/code/nm-prune/node_modules/@pnpm/exec/lib/index.js:46:35)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

`opts` passed in are:
```js
{ args: [ 'install', '--production' ],
  cwd: '/Users/dave/__package_previews__/nm-prune',
  env: { PREVIEW_IS_RUNNING: '/Users/dave/code/nm-prune' } }
```

**Comment by zkochan** [comment]
Seems like `pnpm install` is failing. Check what version of pnpm you have installed (`pnpm -v`). If it is some old version try to update it. The latest is currently `1.23.0`.

If it won't help, try to run `pnpm install --production` in '/Users/dave/__package_previews__/nm-prune' manually and see what happens

**Comment by davej** [comment]
👍 Updating pnpm fixed it.
